# Site settings
title: Gấu Lười
email: ngocdiep.1532@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hệ thống đặt hàng nhập khẩu từ Úc.

baseurl: "" # the subpath of your site, e.g. /blog

copyright:
   name: G&#7845;u L&#432;&#7901;i
   link: '/'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-186317670-1

# Comments
disqus: yes
disqus-shortname: gau-luoi

# #social
# facebook: http://facebook.com/
# quora: http://quora.com/
# twitter: http://twitter.com/
# github: http://github.com/

# #facebook like box
# fb-like-box: yes
# fb-app-id: 
# fb-page-url: https://www.facebook.com/

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

collections_dir: products
collections:
  bio_island:
    output: true
  blackmores:
    output: true
  caruso:
    output: true
  go_healthy:
    output: true
  healthy_care:
    output: true
  milk:
    output: true
  natures_way:
    output: true
  wagner:
    output: true
  others:
    output: true